config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :kind
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :phones, presence:  true
  validates :email, presence:  true
  validates :name, presence:  true, length: { minimum: 3 }
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ITEMS_PER_PAGE = 6
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :create, :edit, :update]
  http_basic_authenticate_with name: "adm", password: "8723", only: [:destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(ITEMS_PER_PAGE)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t("messages.created") }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t("messages.updated") }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t("messages.destroyed") }
      format.json { head :no_content }
    end
  end

  private
    def set_options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk,
                                      address_attributes: [:id, :street, :city, :state],
                                      phones_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.order(:description).page(params[:page]).per(ITEMS_PER_PAGE)
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  BRAZILIAN_STATES = [["Acre", "AC"],
                      ["Alagoas", "AL"],
                      ["Amapá", "AP"],
                      ["Amazonas", "AM"],
                      ["Bahia", "BA"],
                      ["Ceará", "CE"],
                      ["Distrito Federal", "DF"],
                      ["Espírito Santo", "ES"],
                      ["Goiás", "GO"],
                      ["Maranhão", "MA"],
                      ["Mato Grosso", "MT"],
                      ["Mato Grosso do Sul", "MS"],
                      ["Minas Gerais", "MG"],
                      ["Pará", "PA"],
                      ["Paraíba", "PB"],
                      ["Paraná", "PR"],
                      ["Pernambuco", "PE"],
                      ["Piauí", "PI"],
                      ["Rio de Janeiro", "RJ"],
                      ["Rio Grande do Norte", "RN"],
                      ["Rio Grande do Sul", "RS"],
                      ["Rondônia", "RO"],
                      ["Roraima", "RR"],
                      ["Santa Catarina", "SC"],
                      ["São Paulo", "SP"],
                      ["Sergipe", "SE"],
                      ["Tocantins", "TO"]]

  def options_for_states select
    options_for_select BRAZILIAN_STATES, select
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true, html: { class: "basic-grey" }) do |form| %>

  <h1><%= t('forms.contact') %></h1>

  <div class="form-group row">
    <%= form.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :email, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :kind_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.collection_select :kind_id, @kind_options_for_select, :id, :description, {}, { class: 'form-control' } %>
    </div>
  </div>

  <%= form.fields_for :address do |address_fields| %>

    <div class="form-group row">
      <%= address_fields.label :street, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= address_fields.text_field :street, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= address_fields.label :city, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= address_fields.text_field :city, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= address_fields.label :state, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= address_fields.select :state, options_for_states(@contact.address.state), {}, { class: 'form-control' } %>
      </div>
    </div>

  <% end %>

  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>

    <div class="col-sm-100">
      <%= link_to_add_association t('buttons.add_phone'), form, :phones, class: "btn btn-outline-primary" %><br><br>
    </div>

  </div>

  <div class="form-group row">
    <%= form.label :rmk, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :rmk, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.back'), contacts_path, class: "btn btn-outline-info" %></td>
        <td><%= form.submit t('buttons.save'), class: "btn btn-outline-success" %></td>
      </tr>
    </table>
  </div>

  <% if contact.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <script>$.notify("<%= message %>", "error");</script>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <%= f.label :phone, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="col-sm-2">
      <%= link_to_remove_association '[ x ]', f, class: "btn btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div class="basic-grey">

  <h1><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  <script>$.notify("<%= notice %>","success");</script>

  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= @contacts.model.human_attribute_name "name" %></th>
      <th><%= @contacts.model.human_attribute_name "kind" %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.kind.description %></td>
        <td><%= link_to t('buttons.show'), contact, class: "btn btn-outline-success" %></td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact), class: "btn btn-outline-warning" %></td>
        <td><%= link_to t('buttons.destroy'), contact, class: "btn btn-outline-danger", method: :delete, data: { confirm: t('messages.delete_confirmation') } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <div class="pagination-info">
    <%= page_entries_info @contacts %>
  </div>

  <%= paginate @contacts %>

  <br>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.home'), home_index_path, class: "btn btn-outline-info" %></td>
        <td><%= link_to t('buttons.new'), new_contact_path, class: "btn btn-outline-primary" %></td>
      </tr>
    </table>
  </div>

</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="basic-grey">

  <h1><%= t('forms.contact') %></h1>

  <p id="notice"><%= notice %></p>

  <p>
    <strong><%= t('activerecord.attributes.contact.name') %></strong>
    <%= @contact.name %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.contact.email') %></strong>
    <%= @contact.email %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.contact.kind') %></strong>
    <%= @contact.kind.description %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.address.street') %></strong>
    <%= @contact.address.street %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.address.city') %></strong>
    <%= @contact.address.city %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.address.state') %></strong>
    <%= @contact.address.state %>
  </p>

  <% @contact.phones.each do |p| %>
    <p>
      <strong><%= t('activerecord.attributes.phone.phone') %></strong>
      <%= p.phone %>
    </p>
  <% end %>

  <p>
    <strong><%= t('activerecord.attributes.contact.rmk') %></strong>
    <%= @contact.rmk %>
  </p>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.edit'), edit_contact_path(@contact), class: "btn btn-outline-warning" %></td>
        <td><%= link_to t('buttons.back'), contacts_path, class: "btn btn-outline-info"  %></td>
      </tr>
    </table>
  </div>

</div>

app/views/home/index.html.erb
<div class="basic-grey index">
  <div class="title"><%= t('messages.welcome') %></div>
  <table>
    <tr>
      <td><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span><%= link_to "Tipos", kinds_path, class: "btn btn-outline-info" %></td>
      <td><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span><%= link_to "Contatos", contacts_path, class: "btn btn-outline-info" %></td>
    </tr>
  </table>
</div>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true, html: { class: "basic-grey" }) do |form| %>

  <h1><%= t('forms.kind') %></h1>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.back'), kinds_path, class: "btn btn-outline-info" %></td>
        <td><%= form.submit t('buttons.save'), class: "btn btn-outline-success" %></td>
      </tr>
    </table>
  </div>

  <% if kind.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% kind.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<div class="basic-grey">

  <h1><%= "#{t('messages.listing')} #{@kinds.model.model_name.human(count: @kinds.count)}" %></h1>

  <p id="notice"><%= notice %></p>

  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= @kinds.model.human_attribute_name "description" %></th>
      <th><%= t('texts.contact') %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= kind.contacts.size %></td>
        <td><%= link_to t('buttons.show'), kind, class: "btn btn-outline-success" %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind), class: "btn btn-outline-warning" %></td>
        <td><%= link_to t('buttons.destroy'), kind, class: "btn btn-outline-danger", method: :delete, data: { confirm: t('messages.delete_confirmation') } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <div class="pagination-info">
    <%= page_entries_info @kinds %>
  </div>

  <%= paginate @kinds %>

  <br>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.home'), home_index_path, class: "btn btn-outline-info" %></td>
        <td><%= link_to t('buttons.new'), new_kind_path, class: "btn btn-outline-primary" %></td>
      </tr>
    </table>
  </div>

</div>

app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<div class="basic-grey">

  <h1><%= t('forms.kind') %></h1>

  <p id="notice"><%= notice %></p>

  <p>
    <strong><%= t('activerecord.attributes.kind.description') %></strong>
    <%= @kind.description %>
  </p>

  <div class="actions">
    <table>
      <tr>
        <td><%= link_to t('buttons.edit'), edit_kind_path(@kind), class: "btn btn-outline-warning" %></td>
        <td><%= link_to t('buttons.back'), kinds_path, class: "btn btn-outline-info"  %></td>
      </tr>
    </table>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyContacts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>